export { Navbar } from './Navbar'
export { Hero } from './Hero'
export { Features } from './Features'
export { HowItWorks } from './HowItWorks'
export { ReportPreview } from './ReportPreview'
export { Testimonials } from './Testimonials'
export { CTA } from './CTA'
export { Footer } from './Footer'
